spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/watchparty
    username: watchparty
    password: watchparty

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.watchparty: DEBUG
    org.springframework.web.socket: DEBUG
